name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MLX deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libx11-dev libxext-dev libbsd-dev \
            xorg

      - name: Build
        run: make

  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install norminette
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install norminette

      - name: Run norminette
        run: norminette src include/cub3D.h
